(part "CEM-1205-IC"
    (packageRef "CEM1205IC")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Farnell_Part_Number" "")
    (property "Farnell_Price/Stock" "")
    (property "Manufacturer_Name" "Same Sky")
    (property "Manufacturer_Part_Number" "CEM-1205-IC")
    (property "Description" "12 mm, 5 Vdc, 92 dB, Through Hole, Driving Circuit, Magnetic Audio Indicator Buzzer")
    (property "Datasheet_Link" "https://www.sameskydevices.com/product/resource/cem-1205-ic.pdf")
    (property "symbolName1" "CEM-1205-IC")
)
