(part "1825232-1"
    (packageRef "18252321")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "MH1" (symbPinId 4) (portName "MH1") (portType INOUT))
        (port "MH2" (symbPinId 5) (portName "MH2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Farnell_Part_Number" "")
    (property "Farnell_Price/Stock" "")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "1825232-1")
    (property "Description" "Body Features: Actuator Travel .079 INCH | Actuator Orientation Side | Actuator Material Nylon | Actuator Travel 2 MM | Actuator Color Black | Actuator Profile Extended | Product Orientation Right Angle | Configuration Features: Configuration (Pole-Throw) Single Pole - Double Throw | Operating Function On None On | Number of Actuators Single | Number of Positions 2 | Contact Features: Switch Contact Plating Material Silver | Contact Current Rating .2 AMP | Contact Base Material Copper Alloy | Dimensions: Pr")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1308111-1_SWITCHES_CORE_PROGRAM_CATALOG&DocType=Catalog%20Section&DocLang=English&PartCntxt=1825232-1&DocFormat=pdf")
    (property "symbolName1" "1825232-1")
)
