(part "3362P-1-103LF"
    (packageRef "3362P_1")
    (interface
        (port "1" (symbPinId 1) (portName "CCW") (portType INOUT))
        (port "2" (symbPinId 2) (portName "WIPER") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CW") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Farnell_Part_Number" "")
    (property "Farnell_Price/Stock" "")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "3362P-1-103LF")
    (property "Description" "10k, Through Hole Trimmer Potentiometer 0.5W Top Adjust Bourns, 3362")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/SFDatasheet-6/sf-000139931.pdf")
    (property "symbolName1" "3362P-1-103LF")
)
