(part "TL3305AF160QG"
    (packageRef "TL3305AF160QG")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Farnell_Part_Number" "")
    (property "Farnell_Price/Stock" "")
    (property "Manufacturer_Name" "E-Switch")
    (property "Manufacturer_Part_Number" "TL3305AF160QG")
    (property "Description" "SLIDE, 1A, 30VDC DPDT, On-Off-On, Through Hole")
    (property "Datasheet_Link" "https://configured-product-images.s3.amazonaws.com/2D/specs/TL3312NF160Q.pdf")
    (property "symbolName1" "TL3305AF160QG")
)
